services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: false
      WORDPRESS_DEBUG_LOG: false
      WORDPRESS_DEBUG_DISPLAY: false
      WP_DEBUG: false
      WP_DEBUG_LOG: false
      WP_DEBUG_DISPLAY: false
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/fiberpay-payment-gateway

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
